### ISSUE TITLE
type logs + clipboard logs

### ISSUE THREAD

**Issue by hyundotio** [kubernetes-sigs/kui#1244]
In an optional view canvas, it maybe worth adding the history of the clipboard (copy + paste) and/or list of actions taken by the user.

**Comment by myan9** [comment]
Thanks! We do have a `history` command of listing the commands that user typed.  Also thanks for the clipboard logs suggestion!

**Comment by hyundotio** [comment]
Oh okay! I don't think the clipboard management should be a separate thing; I think it can be an entry / in-line item in the history. It would be nice to retain some of things I've been trying to carry over from KUI to another application in-case I lose it.
