### ISSUE TITLE
when "suspending" a foreground process, open a new tab?

### ISSUE THREAD

**Issue by rabbah** [kubernetes-sigs/kui#1297]
this is a feature request/question - in a terminal it's common to suspend a process to run some other command then fg the old process again... it would be nice to support something like this in the shell, maybe suspend could just open a new tab, and push the current tab to a stack, so that fg later could pop the last used tab and switch to it.

a suggestion, there could be better ways of dealing with bg/fg operations

**Comment by starpit** [comment]
i like the idea here
