### ISSUE TITLE
properly implement ! to repeat commands

### ISSUE THREAD

**Issue by rabbah** [kubernetes-sigs/kui#1300]
<img width="350" alt="57195796-9c1a8400-6f24-11e9-84c3-cbb6890d5ed2" src="https://user-images.githubusercontent.com/4959922/57200275-fe40ac80-6f57-11e9-9984-5169feefbaf9.png">
<img width="210" alt="57195803-a63c8280-6f24-11e9-8d4d-52288eae141e" src="https://user-images.githubusercontent.com/4959922/57200276-ff71d980-6f57-11e9-9944-f3b9f52c648f.png">

also ! e doesn't work as expected.

**Comment by starpit** [comment]
for now, it `!!`

**Comment by rabbah** [comment]
<img width="385" alt="Screen Shot 2019-05-09 at 12 36 40 AM" src="https://user-images.githubusercontent.com/4959922/57427605-9659c280-71f2-11e9-88f5-763e3532f81e.png">
