### ISSUE TITLE
pushd/popd do not work

### ISSUE THREAD

**Issue by rabbah** [kubernetes-sigs/kui#1348]
<img width="331" alt="Screen Shot 2019-05-08 at 5 58 42 PM" src="https://user-images.githubusercontent.com/4959922/57411230-f2a0f000-71ba-11e9-8a16-d7522affa2ad.png">

**Comment by starpit** [comment]
thanks for the bug report! this issue stems from the way kui interacts with the underlying bash. a closely related issue: #180

**Comment by glensc** [comment]
the way the shell integration really sucks for me. my .bash_profile/.bashrc is very heavy and they set various state. it's, even so, bad that it even messes up keyboard interactivity (input loss)

would be better if the shell pty is always created and input somehow directed to there, keeping the same shell command running.

**Comment by starpit** [comment]
hi elan! yes, agreed. this is on our list to fix #1247 

we have a stop-gap that can help with slow-loading bashrc: you can guard the heavy stuff with `if [ -z "$KUI" ]; then ...; fi`

for example, some of my heavy lifters are for kubectl tab completion; kui provides a bit of this itself, and so disabling the bashrc implementation doesn't affect my terminal experience.

but, agreed, this is a stop-gap measure! thanks for the feedback, we really appreciate it!
