### ISSUE TITLE
Multiple KUBECONFIGs ?

### ISSUE THREAD

**Issue by lemaral** [kubernetes-sigs/kui#1734]
Nice work :)
I found a confusing issue (on MacOS at least):
Running multiple kui shell from zsh sessions with different KUBECONFIGs seem to always keep the first KUBECONFIG. Even closing all windows in the Kui Electron application before relaunching kui shell will still keep the very first one.

**Comment by starpit** [comment]
hello, thanks for the feedback! confirmed.

i believe this is related to #1470. i'll push this one up in priority.

thanks!
