### ISSUE TITLE
attempt to internationalize k8s messages?

### ISSUE THREAD

**Issue by showeimer** [kubernetes-sigs/kui#2336]
Recommend this library:  https://momentjs.com/

Maybe just only in locations that are titles/subtitles/headings ?  I don't think it would be normal to convert a date or time inside some presentational metadata like in the yaml tab.

**Comment by starpit** [comment]
can you be more specific in identifying UI elements that are incorrect? thanks

**Comment by showeimer** [comment]
Here are some examples that I can think of from sidecar:

<img width="524" alt="Screen Shot 2019-08-16 at 11 20 02 AM" src="https://user-images.githubusercontent.com/26075187/63178404-fa70fb80-c017-11e9-9006-d2f6aa0c4fc7.png">
<img width="251" alt="Screen Shot 2019-08-16 at 11 20 16 AM" src="https://user-images.githubusercontent.com/26075187/63178405-fa70fb80-c017-11e9-8ff0-16a2fbbc89c1.png">
<img width="224" alt="Screen Shot 2019-08-16 at 11 20 22 AM" src="https://user-images.githubusercontent.com/26075187/63178406-fa70fb80-c017-11e9-8afc-277f88c545f4.png">

**Comment by starpit** [comment]
anything that appears as a Message in a kubernetes table comes directly from the kubernetes resource models. these are more or less random strings emitted by the managing operator, and so not under kui control.

do you have any other examples?

**Comment by showeimer** [comment]
@starpit I would say it is normal from a front-end perspective to transform data from a back-end to be presented in a different format.  Consider booleans rendered as green or red icons, calculating age or time left of something based on a provided timestamp, etc.

Here is some IBM globalization reference material:

https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/GIG/page/Cultural%20Data%20format%20and%20Data%20handling?section=2

**Comment by starpit** [comment]
got it. we will treat this as ann enhancement. it would require parsing out the text, because the Messages field truly is random text emitted by the operator. there is no governance as to its content. in particular, it is only certainly not going to be just date strings.

**Comment by showeimer** [comment]
Sounds good to me!
