### ISSUE TITLE
alias does not work as expected

### ISSUE THREAD

**Issue by rabbah** [kubernetes-sigs/kui#2399]
**Describe the bug**
Create a new alias and then use it, the alias is not recognized.

**Steps to reproduce the behavior**

❯ alias x=ls
❯ x
Command not found: x

**Expected behavior**
`x` should behave as `ls`.

**Screenshots**
<img width="334" alt="Screen Shot 2019-08-16 at 11 38 00 PM" src="https://user-images.githubusercontent.com/4959922/63206250-e7dddd00-c07e-11e9-91d2-96b78428a269.png">

**Comment by starpit** [comment]
this has the same underlying issue as #1348
