### ISSUE TITLE
open url?

### ISSUE THREAD

**Issue by rabbah** [kubernetes-sigs/kui#2407]
you can `open file` how about `open url`?

<img width="704" alt="Screen Shot 2019-08-17 at 10 39 51 AM" src="https://user-images.githubusercontent.com/4959922/63213524-5fd9f080-c0db-11e9-8fad-8842c543e29a.png">

additionally is it possible to detect the url and make it clickable always?
in the screen shot none of the urls are clickable.

**Comment by starpit** [comment]
both sound good to me!
