### ISSUE TITLE
Selection buttons in table output for `kubectl config get-contexts` not working

### ISSUE THREAD

**Issue by dgrove-oss** [kubernetes-sigs/kui#2467]
**Describe the bug**
`kubectl config get-contexts` outputs a nicely formatted table with radio-style selection buttons next to each of the defined contexts.  I expect to be able to click on a button and have it change the current context.  Clicking on any of the buttons appears to do nothing.  See attached movie

![radio-buttons-do-nothing](https://user-images.githubusercontent.com/5099100/63466450-46191000-c431-11e9-8ef0-b989f5f7487a.gif)
.

**System**

- Kui version: 2.34.0-dev.3876.20190819012103
- Operating system: MacOS 10.14.6

**Comment by myan9** [comment]
Thanks for reporting ! Currently `kubectl config get-contexts` only returns a pretty table. The interactive version of this command is `contexts`, which calls`kubectl config get-contexts`  and adds onclick handler for you to switch context. We need to enhance the original `kubectl config get-contexts` table, thanks!

**Comment by dgrove-oss** [comment]
Thanks for clarifying; `contexts` works for me.
