### ISSUE TITLE
Releases via HomeBrew

### ISSUE THREAD

**Issue by docwhat** [kubernetes-sigs/kui#2586]
It would be nice to have a HomeBrew [formula](https://docs.brew.sh/Formula-Cookbook) for KUI to keep it up-to-date on MacOS.

**Comment by LouisStAmour** [comment]
I've submitted a PR for a homebrew cask at https://github.com/Homebrew/homebrew-cask/pull/84210

Note that it requires user effort to add a path to PATH. If https://github.com/IBM/kui/pull/4878 is merged, this can be cleaned up by another PR to the cask repo.

**Comment by starpit** [comment]
this is great @LouisStAmour thanks!!

**Comment by LouisStAmour** [comment]
Good news, Kui is on Homebrew! It doesn't yet install a Kubectl plugin but could after we work out #4878

**Comment by LouisStAmour** [comment]
Sorry it's taken this long :) But I've finally found the time -- and remembered -- to submit a PR to automatically install the kubectl-kui binary. https://github.com/Homebrew/homebrew-cask/pull/84742

**Comment by LouisStAmour** [comment]
And the above PR is merged. So we can mark this issue **Done**!

**Comment by LouisStAmour** [comment]
@starpit We can probably close this issue? Unless you'd like to track #5022 here?

**Comment by LouisStAmour** [comment]
Given the new repo, we might want to update the Homebrew cask URL at https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/kui.rb

if I have time I’ll do it, but if someone gets to it before me, that’s great too! :)
