### ISSUE TITLE
Drag and Drop files is not supported

### ISSUE THREAD

**Issue by JeyanthVictory** [kubernetes-sigs/kui#2814]
Hi,

In Microsoft Edge, Drag and Drop is not supported as far I have seen. As discussed in [Stackoverflow](https://stackoverflow.com/a/32466075/9133493), this has been fixed and bundled up for use. It seems it's not working. I am using MS Edge Browser with version 44.17763.1.0. You can able to reproduce the reported issue in [this ](https://stackblitz.com/edit/typescript-kobcul?file=index.ts)sample.

Hope I get some solution.

Thanks in advance.

**Comment by myan9** [comment]
@JeyanthVictory  I might have missed something, but...there's no functionality in Kui related to Drag and Drop. Which feature are you referring to?
