### ISSUE TITLE
the download link is not compatible with curl

### ISSUE THREAD

**Issue by sdake** [kubernetes-sigs/kui#3274]
**Describe the bug**
It is very useful to use curl to download things rather than rely on the browser to do so.

This is a common pattern by advanced developers to download to a different machine than where the browser is running.

**Steps to reproduce the behavior**
1. Stevens-MacBook-Pro-2:release sdake$ curl -LO https://macos-tarball.kui-shell.org/
curl: Remote file name has no length!

**Expected behavior**
curl should be usable.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version: from README.md
- Operating system: MacOS

**Comment by starpit** [comment]
hi, thanks for raising this issue. does this work for you?

```sh
curl -L https://macos-tarball.kui-shell.org | tar jxf -
```

note that this has no `-O`; the example on the installation.md page i believe has the no-dash-O suggestion: https://github.com/IBM/kui/blob/master/docs/installation.md#example-download-for-macos-double-clickable

let me know if that works for you!

**Comment by sdake** [comment]
> hi, thanks for raising this issue. does this work for you?
> 
> ```shell
> curl -L https://macos-tarball.kui-shell.org | tar jxf -
> ```
> 
> note that this has no `-O`; the example on the installation.md page i believe has the no-dash-O suggestion: https://github.com/IBM/kui/blob/master/docs/installation.md#example-download-for-macos-double-clickable
> 
> let me know if that works for you!

@starpit thanks for the suggestion, however, I am not piping anything from a curl command in my shell - especially into tar...

**Comment by sdake** [comment]
I noticed this looking at the source code:
https://github.com/IBM/kui/blob/master/tools/install.sh#L4

That is probably ok for some people, but not ok for a whole lot of other people. :) I understand why you are keen to get to this model.  I'd encourage you to provide an easy to comprehend mechanism for downloading (in the future signed) binaries via `curl -LO`.

Cheers
-steve

**Comment by starpit** [comment]
thank you for these great thoughts. in the near future, we are hoping to ship the parts of kui in a more componentized fashion via `krew`. this repo will cover the kubectl enhancements: https://github.com/kui-shell/plugin-kubeui

**Comment by LouisStAmour** [comment]
I think we can close this ticket given releases have moved to GitHub?
