### ISSUE TITLE
Kui shell does not honor HERE docs

### ISSUE THREAD

**Issue by sdake** [kubernetes-sigs/kui#3281]
**Describe the bug**
Loads of websites have a bunch of cut and paste using HEREdoc in bash.  This results in all kinds of bad output from Kui.

**Steps to reproduce the behavior**

1. Open KUI
1. Paste a HERE doc into the shell (I used: https://istio.io/docs/tasks/observability/gateways/)
1. The here doc rendering is shown in the screenshot.
1. I had to run the HERE doc creation separately in bash to get it to apply...

**Expected behavior**
HEREdoc processed.

**Screenshots**
<img width="1275" alt="Screen Shot 2019-11-24 at 11 53 00 PM" src="https://user-images.githubusercontent.com/755849/69518869-db86dd00-0f15-11ea-86b8-c8eadf4e8f18.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version: version doesn't display
- Operating system: MacOS 15.0.1.

**Comment by loraxipam** [comment]
This may also be relevant to the problem I see with bash "for" loops not working from the command line. See below:

![image](https://user-images.githubusercontent.com/17756560/86935819-4387dd80-c10b-11ea-8de5-c5e2ca3df422.png)

**Comment by starpit** [comment]
Thanks for the ping on this. The bug here is in the OnPaste.tsx logic. It prematurely splits the pasted input into multiple lines.
