### ISSUE TITLE
error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cleverlzc** [kubernetes-sigs/kui#3426]
**Describe the bug**

Ihave installed  libgdk_pixbuf-2.0.so.0，but installed  gdk-pixbuf2-2.36.5-1.h1.i686 version，Kui only  libgdk_pixbuf-2.0.so.0 available？？

```
yum install -y libgdk_pixbuf-2.0.so.0
Package gdk-pixbuf2-2.36.5-1.h1.i686 already installed and latest version
```

and , i found:
```
ll /lib/libgdk_pixbuf*
lrwxrwxrwx 1 root root     29 Dec 31 10:35 /lib/libgdk_pixbuf-2.0.so.0 -> libgdk_pixbuf-2.0.so.0.3600.5
-rwxr-xr-x 1 root root 173176 Jan  1  2018 /lib/libgdk_pixbuf-2.0.so.0.3600.5
```

But the error keep going...

How can I solve this problem? Thank you.

**Steps to reproduce the behavior**

```
Linux version：  3.10.0-327.62.59.83.h120.x86_64 #1 SMP Mon Jul 9 00:00:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
installation package:   Kui-linux-x64.zip
```

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version:
- Operating system:

**Comment by starpit** [comment]
hello, thanks for the bug report! as of this writing, Kui should have the same X/gdk/etc. prerequisites as chromium 76 (which in turn comes from electron version 6 -- the version of electron Kui uses, as of this writing). perhaps if you can get chromium 76 installed, the necessary prereqs will flow in?

which linux distribution are you using?

thanks!

**Comment by pfelwor** [comment]
Hi, looks like you have installed ibgdk_pixbuf-2.0.so.0 for the wrong architecture (i686) since your system is running on x86_64?
