### ISSUE TITLE
Please support value attribute for bottom command input bar element

### ISSUE THREAD

**Issue by showeimer** [kubernetes-sigs/kui#3484]
We would like the value attribute added to the input element for the bottom command input bar; this will help make writing tests easier for our custom client; seems the text value is hidden in a shadow dom div currently that can't be accessed by E2E test frameworks.

**Comment by starpit** [comment]
at least in the core, the bottom input is a plain `<input>` element. 

https://github.com/IBM/kui/blob/master/packages/core/templates/index.html#L402

is it possible that your override does something here?

**Comment by showeimer** [comment]
@starpit 

We actually have a dependency on the override to make the tests run in a more stable/efficient manner.  While working on the KUI upgrade to 5.7.x, I was making changes to our test suite to be less dependent on the overriding plugin but was running into an issue where the native KUI input bar did not include the value attribute on the input element.  We have a need to stabilize our tests by waiting for the test framework to finish "typing" and verify the text before the command gets executed with something like this:

#### Nightwatch.js
```js
  this.waitForElementPresent('.kui--input-stripe input[value="clear"]')
  this.enter()
```

Running something like `document.querySelector(''.kui--input-stripe input').value` in the browser console will yield the the value of the input element, but since the test framework utilizes this kind of CSS selector targeting strategy; the code will break here and we start having stability issues with our tests.  I concede that there are probably issues with the test framework itself; but I think it would be good to have this available for other persons writing custom clients and their own tests.  

I can force the test framework to pause/hold for X amount of seconds, but the time required is a bit arbitrary and I think for optimization/performance reasons it's better to just ask the test framework to work with the code above.

---

#### Other things that might help tests:

1.  `id` tag on the command input bar and all other interact-able components (buttons, etc).
2.  REPL results should also have the value attribute on those input elements; for example execute any kubectl command and inspect that text in the REPL; there's no attribute on that corresponding input element that says what the command was.
3.  Similar to #2, it would be nice if the container divs for REPL results also had some data attribute that indicates what the command executed was.  The divs just have this information:  `<div class="repl-block valid-response" data-base-class="repl-block" data-input-count="0">`.

---

### Native KUI:

<img width="1650" alt="Screen Shot 2020-01-16 at 11 04 54 AM" src="https://user-images.githubusercontent.com/26075187/72541278-3d95fb80-3850-11ea-8bbc-6258fb36a396.png">


### With our hijack:

<img width="1651" alt="Screen Shot 2020-01-16 at 10 50 13 AM" src="https://user-images.githubusercontent.com/26075187/72540136-759c3f00-384e-11ea-8304-5c58c61bfe24.png">
