### ISSUE TITLE
start proxy with `https`  mode failed as `error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt`

### ISSUE THREAD

**Issue by Xiaohua-Shen** [kubernetes-sigs/kui#4271]
**start proxy with `https` mode failed**
it displayed `error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt` and exit.

**Steps to reproduce the behavior**
in ubuntu 16.04, execute below steps to start proxy
```
git clone https://github.com/IBM/kui \
    && cd kui \
    && npm ci \
    && sed -i '/^image$/d' node_modules/@kui-shell/proxy/build-docker.sh \
    && ./packages/webpack/bin/ssl.sh  \
    && npx kui-build-webpack \
    && npx kui-build-docker-with-proxy \
    && mv .keys dist/webpack/kui \
    && cd dist/webpack/kui \
    && npm link ./app --no-package-lock \
    && cd node_modules/node-pty-prebuilt-multiarch \
    && npm run install \
    && cd ../.. \
    && PORT=8076 KUI_PROXY_EXTERNAL_PORT=443 KUI_PROXY_COHOSTED=true npx start-proxy
```

it failed at
```
error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
```

**Expected behavior**
The proxy should be started successfully.

**System**

- Kui version:  current master branch
- Operating system: ubuntu 16.04, use node 10

**Comment by starpit** [comment]
currently, https is not supported. the current assumption is that kui will be deployed as part of a larger context, which will provide its own certificates. if this is not sufficient, PRs welcome!
