### ISSUE TITLE
WebApp - Make KUI responsive for mobile?

### ISSUE THREAD

**Issue by showeimer** [kubernetes-sigs/kui#4425]
@TheRealHaoLiu and @hanqiuzh mentioned it might be nice to make the KUI UI responsive for mobile.  Terminal experience on mobile doesn't really exist, so this might be interesting?

**Comment by starpit** [comment]
agreed. we have some bits of support for viewport reactivity, as shown in the attached gif. i'd love to hear about additional opportunities here!

![reactive kui](https://user-images.githubusercontent.com/4741620/80763535-b9206d80-8b0c-11ea-8f50-397e57ca3b77.gif)
