### ISSUE TITLE
Feature - Create kube resource templating in monaco editor

### ISSUE THREAD

**Issue by showeimer** [kubernetes-sigs/kui#4470]
It would be nice when I want to create a new kubernetes resource if I can just do something command like:

`kubectl create deployment`

and the monaco editor would slide out with a deployment yaml template already set up.  This can also be extended to CRDs by fetching the CRD and dynamically creating the template.

**Comment by starpit** [comment]
that's a nice idea. maybe we can link it in with kustomize, too, at some point.

**Comment by starpit** [comment]
would some of `odo` help here? it seems like, in this example: https://docs.openshift.com/online/starter/cli_reference/openshift_developer_cli/creating-a-single-component-application-with-odo.html

the only "out of band" step is the `git clone` of the template?

**Comment by showeimer** [comment]
Looks like that's for scaffolding applications not a kube resource?
