### ISSUE TITLE
Feature - plugin to make building http requests easier

### ISSUE THREAD

**Issue by showeimer** [kubernetes-sigs/kui#4477]
@hanqiuzh and I were doing some work and were having to build curl commands to test some API behaviors.  Sometimes it's hard to remember the syntax or flags needed to write curl commands or whatever http client tool you want to use.  If KUI had a way to help build/make http requests like Postman can do and make those requests inside KUI, that might be a cool feature?

**Comment by starpit** [comment]
this sounds like a neat idea!

**Comment by ujibang** [comment]
@showeimer I just release HTTP Shell v0.0.1 that is build from Kui v9.0.0 that is

> A CLI tool that provides developers a modern alternative to http clients for interacting with APIs.

Find it at https://github.com/SoftInstigate/http-shell

@starpitinterested on merging the plugin into kui? let me know...

**Comment by starpit** [comment]
hey, so sorry for the delay! we'll check it out. it sounds interesting.

**Comment by myan9** [comment]
@ujibang Great! We are glad to merge http-shell into Kui. Please feel free to PR it. Recently, we've been enhancing Sidecar to be more terminal involved (you can find the proposal here: https://github.com/IBM/kui/issues/6007). We're going to try it out with http-shell. The `get` command result will then be shown inline, just like the `set auth` command. We will soon release a live version of this for feedback. We'll really appreciate it if you could give us some feedback on this.

**Comment by starpit** [comment]
The "inline sidecar" work currently has an open PR: #6008. In addition to the screenshots in the associated issue, we have published a read-only form for perusal to http://next.kui.tools; from there, you can browse some of the notebooks, or, better, you can link directly in to one of the kubernetes example notebooks: http://q.next.kui.tools/index.html?command=replay%20-c%20/kui/kubernetes/crud-operations.json

btw, this ability to host a read-only Kui as a static single-page web app, hosted in a plain object storage bucket is something you can also use. i think we're ready to publicize this avenue (it's just a plain build, using the plugin-client-notebook client, and copied to an s3 bucket). you could craft your own notebooks to help publicize your tool. we can chat about that separately.

Let us know what you think of the inline sidecar!

<img width="1442" alt="Screen Shot 2020-10-20 at 8 08 20 PM" src="https://user-images.githubusercontent.com/4741620/96657361-03daaf80-1310-11eb-9e00-bb7fe937770e.png">

**Comment by ujibang** [comment]
I went through the proposal #6007 about inline sidecars and also looked the screenshot in the PR https://github.com/SoftInstigate/http-shell/pull/1

![](https://user-images.githubusercontent.com/21212160/96770834-da249580-13ae-11eb-88fb-1e814c425f4e.png)

Well, inline sidecars are definitely the way to go to show response data! This means that different responses will linearly be available in the shell, a great improvement.

The online notebooks are super cool! I will create a notebook and publish it for sure. Notebooks really make documenting some features of our product [RESTHeart](https://restheart.org) quite effective. Being RESTHeart an API server, sometimes it takes different steps requests to explain some use cases, and a notebook can definitely visualize the process very well!
