### ISSUE TITLE
Detail window still in dark theme even light is selected

### ISSUE THREAD

**Issue by haf-tech** [kubernetes-sigs/kui#5023]
**Describe the bug**
The light theme is selected, however the detail window (right side) is still in dark mode.
Reload, re-install does not help.
Especially for the flow diagrams for pipelines is the dark theme not helpful

**Steps to reproduce the behavior**

1. Select "light" theme
2. click on item to see the details on the right side

**Expected behavior**
All areas, windows considering the theme selection

**Screenshots**
See screenshot. I even changed the macOS theme to light only to be sure ;-)
![Screenshot 2020-06-27 at 19 32 41](https://user-images.githubusercontent.com/29369954/85928420-15a1ce00-b8ad-11ea-916f-dd78b60a3399.png)

**Code snippets**
n/a

**System**

- Kui version: 8.10.4
- Operating system: macOS 10.14

**Comment by starpit** [comment]
thanks for the bug report! and apologies for the delay in responding. the two-tone presentation is intentional, but the low contrasts in the flow view certainly are not. thanks!
