### ISSUE TITLE
Make it working with WSL on Windows

### ISSUE THREAD

**Issue by dex4er** [kubernetes-sigs/kui#5110]
I would like to use kubectl from WSL rather than native. For me and for a lot of developers I know the default shell on Windows is bash in WSL. Then I have two different contexts: 1st in WSL and 2nd in KUI.

It would be easier if KUI could be switched to kubectl from WSL (could run `wsl kubectl` rather than `kubectl.exe`) or could just parse the output from any kubectl command correctly:

![Annotation 2020-07-10 132038](https://user-images.githubusercontent.com/174367/87149261-2dffe880-c2b0-11ea-8d9d-cabb1b7548b3.png)

**Comment by starpit** [comment]
greetings, and thanks for the great feedback. this makes sense. we will need to get a bit more experience with WSL before we can size this up.

**Comment by dex4er** [comment]
I found some workaround:

```sh
printf "@echo off\r\nwsl kubectl %%*\r\n" > /mnt/c/Windows/System32/kubectl.bat
```

**Comment by nikopen** [comment]
/remove-lifecycle rotten

@starpit WSL now supports linux GUI apps: https://github.com/microsoft/wslg  
 however Kui asks for some additional UI shared libraries:  
```
libnss3.so
libXcursor.so.1
libasound2
```

then when installed it fails to start with: `The futex facility returned an unexpected error code.Aborted`

would be great to have native WSL support :)

**Comment by starpit** [comment]
Hi @nikopen thanks for bringing this up! Do you have a stack trace perhaps?
