### ISSUE TITLE
direnv support

### ISSUE THREAD

**Issue by 99** [kubernetes-sigs/kui#5485]
Hi,
thank you for the interesting tool. Found it very handy is some cases.
I was wondering is it possible for this tool to integrate with direnv https://direnv.net/?

Thank you,
Natalie

**Comment by starpit** [comment]
hello natalie, thanks for the interesting feedback.

this does indeed seem like an intriguing approach. we have contemplated the value of this on several occasions: having a separate kubernetes context per Kui tab, for example; and then possibly color-coding the bottom status stripe depending on your current context.

if direnv can help with this, that would be nice!

**Comment by starpit** [comment]
oops, fumble-clicked the wrong button! re-opening...
