### ISSUE TITLE
Provide search capability on pod details Logs tab

### ISSUE THREAD

**Issue by mark-nc** [kubernetes-sigs/kui#5570]
Today when clicking on a pod to get the pod details sidecar, the Logs tab will show either the streaming logs or not (if the user disables streaming).  While this is useful, if there is a lot of log output, it may be hard to locate specific log statements the user cares about.  

If using a normal text based terminal window, a user might run a logs command piped through `grep someRegularExpression`.  Typing such a command in a Kui session opens up the pod details sidecar to the Logs tab, but that results in an error that grep does not understand the `--tail` parameter.  This is not surprising as the Logs tab is not designed to work with piped commands.  The user task, however, is a desire to search/filter log output to find something specific.  It would be useful for the Logs tab to support some type of search feature where the user could enter a search string and then have the Logs tab filter the output to show the matches (and then be able to clear the search).

Some UX design work would be needed to have this follow similar other search patterns, but the feature would be useful.

**Comment by berenss** [comment]
adding a 'filter' field to the streaming log feature, would be a very nice capability for an Ops/SRE

![image](https://user-images.githubusercontent.com/20711730/92513879-9e56b780-f1d6-11ea-9833-5561a10aa996.png)

**Comment by starpit** [comment]
nice, thanks for the great ideas!

**Comment by starpit** [comment]
Thanks for the issue, sorry for the delay here. 

Is the request for find/highlight text? Or is it for filtering log lines (i.e. on a line-by-line basis) based on whether a given line contains a given pattern? I think the latter, but want to make sure. Thanks!

**Comment by starpit** [comment]
We could also offer a Download button, to help with employing external tools.

**Comment by berenss** [comment]
Yes it’s the latter, effectively a log tail with a grep. So having a filter box where I can I put the grep value and then the log follow will show me a reduced set of entries based on what is in the filter box. 

We have another ctl being included for which a download capability would be very ideal! Not sure if our web browser based implementation can handle that thou.

**Comment by starpit** [comment]
@berenss thoughts?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4741620/120025895-558e9b00-bfbf-11eb-8fdd-d26a6aa34d23.gif)

**Comment by berenss** [comment]
Love it! Thx 🚀
