### ISSUE TITLE
Remote Shell using SSH

### ISSUE THREAD

**Issue by maltron** [kubernetes-sigs/kui#5924]
Here is a killer feature that I would love to see implemented on KUI:

VSCode has one extension called: Remote Development using SSH
https://code.visualstudio.com/docs/remote/ssh

It allows you directly from VSCode to work remotely on a server through SSH. The benefits in using a. remote environment (especially for Kubernetes/OpenShift) are huge because it allows you to get closer to your cluster and get feedback faster and at the same time, providing a local experience.

**Comment by starpit** [comment]
thanks for the suggestion! it looks interesting.
