### ISSUE TITLE
How to fully display the UsageModel in case of UsageError and how to handle the -h option in commands?

### ISSUE THREAD

**Issue by ujibang** [kubernetes-sigs/kui#6002]
I have trouble getting the usage being printed when a command specify the option `-h`

I'm using kui 9 deriving my app  ([HTTP Shell](https://github.com/softInstigate/http-shell))  from the [AnimalApp Kui skeleton project](https://github.com/IBM/kui/tree/master/docs/example/AnimalApp) with the following plugins:
- plugin-bash-like
- plugin-carbon-themes
- plugin-client-common
- plugin-core-support
- plugin-electron-components
- plugin-git
- plugin-proxy-support

With a 6.0.5 release of kui, it was enough throwing an UsageError to get the full information held in UsageModel being pretty printed.

With v9, `throw new UsageError({ message: errorMsg(usage), usage: usage });` just displays the `message`.

When using the `-h` option in any command, nothing prints out and the actual command does not get even get invoked.

- Is there a way to have the UsageModel associated with a command to be fully displayed (as in previous releases, not just the message)? 

- How to get the `-h` option to work, i.e. displaying the UsageModel?

**Code snippets**

in the following snippets I register the command `set url`. When it is called without one argument, the UsageError is thrown. But nothing gets printed.

#### command
```
const setUrlCmd = async ({ argvNoOptions: args }: Arguments) => {
  if (!args || args.length < 3) {
    throw new UsageError({ message: errorMsg(usage), usage: usage });
  } else {
    Store().setItem("url", args[2]);

    return 'ok';
  }
};

export default async (registrar: Registrar) => {
  registrar.listen('/set/url', setUrlCmd, {
    usage: usage,
    noAuthOk: true
  });
};
```

#### usage
```
export const setUrlUsage: UsageModel = {
  title: "set url <url>",
  header: "sets the base-url for requests",
  example: "set url http://127.0.0.1:8080",
  detailedExample: [
    {
      command: "set url http://127.0.0.1:8080",
      docs: "sets the base-url as on localhost port 8080"
    }
  ],
  required: [
    { name: "url", docs: "the URL of API endpoint", file: false, positional: true }
  ]
};
```

### plugins.ts

```
import seturl from './lib/cmds/set-url';

export default async (registrar: Registrar) => {
 await Promise.all([seturl(registrar), ... ]);
}
```

**Comment by starpit** [comment]
Thanks for the issue.  Sorry for the delay, we've been working on another issue. We'll wrap back on this in a day or two!
