### ISSUE TITLE
Missing OpenShift Client (oc command)

### ISSUE THREAD

**Issue by rbo** [kubernetes-sigs/kui#6356]
Unfortunately `oc` command is not available.  (OpenShift Client)

```
oc get nodes
spawn oc ENOENT
```
![Screenshot 2020-12-08 at 2 35 10 PM](https://user-images.githubusercontent.com/36604/101490638-eebeec00-3962-11eb-8bcd-fb2f6160716b.png)

Please add `oc` client too.

**Comment by myan9** [comment]
Hi @rbo , we do have
![Screen Shot 2020-12-08 at 10 29 23 AM](https://user-images.githubusercontent.com/21212160/101503583-3f711d80-3940-11eb-8445-0b249263b1e5.png)
 supports for `oc`. Do you have oc executable installed on your machine? Can I know how you invoke Kui and your environment?

**Comment by starpit** [comment]
Hmm, yeah, is it possible that somehow Kui did not pick up the proper PATH? For both @myan9 and I, `oc` is in /usr/local/bin, and Kui seems to have found it.

**Comment by rbo** [comment]
Installation follows straigt the documentation:
```
curl -L https://macos-tarball.kui-shell.org/ | tar jxf -
export PATH=$PWD/Kui-darwin-x64/Kui.app/Contents/Resources:$PATH
```

oc client is installed but in my "personal bin" 
```
rbohne@dune:~ $ type oc
oc is /Users/rbohne/bin/oc
```
I added add `~/.bin` to $PATH via `~/.bashrc`

Copy oc into /usr/local/bin solved the problem.

**Comment by rbo** [comment]
Ah kubectl was available in `/usr/local/bin` because of Docker.
```
/usr/local/bin/kubectl -> /Applications/Docker.app/Contents/Resources/bin/kubectl
```

So Kui use always the local kubectl and oc cli tools?

A more intuitive error message would be helpful. `spawn oc ENOENT` is not very intuitive.

**Comment by starpit** [comment]
Thanks @rbo for the extra information. It seems like Kui was not finding your ~/.bin addition to PATH? Could you try this, in Kui: `printenv PATH`. 

Also: are you using zsh? or bash? or? thanks!

**Comment by rbo** [comment]
@starpit 
```
printenv PATH

bash: alias: Source: not found
bash: alias: .bash_profile: not found
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS
```
My default shell is bash.
