### ISSUE TITLE
Integrate Dataset Lifecycle Framework to support S3+NFS Data Sources

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes-sigs/kui#6374]
Last year or so we have been working on DLF ( https://github.com/IBM/dataset-lifecycle-framework ) which introduces a new CRD Dataset. This works as a pointer to an existing remote S3/NFS Datasource and we also generate a PVC for it which users can mount directly to their pods and access the bucket/nfs data via a mount-point. Would love to explore if it would be useful to integrate it with kui or develop a plugin for it.

**Comment by starpit** [comment]
Howdy @YiannisGkoufas, thanks for the interesting idea, we really appreciate it.

We recently added a fairly simple/primitive VFS layer to Kui. Would this be a place that you could target for enhancement? With Kui today, one may do the following, assuming Kui is able to identify your S3 credentials:

```sh
ls /s3/aws/myBucket/*.txt
ls /s3/minio/myOtherBucket
ls /s3/ibm/myThirdBucket
mkdir /s3/ibm/myThirdBucket
cp /s3/aws/myBucket/*.txt /s3/ibm/myThirdBucket
```

etc. Kui tries to intuit the access credentials for these providers... Is this something you could make more real?

**Comment by starpit** [comment]
Here is the VFS interface: https://github.com/IBM/kui/blob/master/plugins/plugin-bash-like/fs/src/vfs/index.ts#L42

and here is the s3 impl: https://github.com/IBM/kui/blob/master/plugins/plugin-s3/src/vfs/index.ts#L38

**Comment by YiannisGkoufas** [comment]
Hi @starpit ! Just to add a bit more clarification about what our project does. We offer a mountpoint for the bucket but only inside pods running on Kubernetes, while the plugin-s3 it's about giving the same functionality to the KUI user/developer.
Would be interesting to explore how the user can interface with s3 buckets that are defined in Kubernetes as Datasets.
One idea that comes to mind is the same way that the user can get information about the pod when invoking
`kubectl get pods` and clicking on the pod, the same way they could get data-related information (size,list of files, preview of contents) when invoking `kubectl get datasets` and clicking on the S3/NFS data sources
