### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by haf-tech** [kubernetes-sigs/kui#7239]
**Describe the bug**
Receiving `Unexpected end of JSON input` for some commands, like get secrets or cm

**Steps to reproduce the behavior**

1. `oc get secrets` OR `oc get cm` OR `k get cm`
2. results in `Unexpected end of JSON input`

**Expected behavior**
Secrets or CM
Same commands returns expected results in a normal terminal

**Screenshots**
![Screenshot 2021-03-28 at 19 26 28](https://user-images.githubusercontent.com/29369954/112761480-d222ee80-8ffb-11eb-8381-414ca146de65.png)
![Screenshot 2021-03-28 at 19 26 49](https://user-images.githubusercontent.com/29369954/112761487-d8b16600-8ffb-11eb-9653-74cf727fd186.png)

**System**
- Kui version: 10.2.1
- Operating system: MacOS
- OpenShift Cluster 4.6.22

**Comment by starpit** [comment]
Thanks for the bug report! Sorry for the delay in responding. What version of `kubectl` and `oc` do you have?

**Comment by haf-tech** [comment]
@starpit 
> Thanks for the bug report! Sorry for the delay in responding. What version of `kubectl` and `oc` do you have?

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+7d0a2b2", GitCommit:"7d0a2b269a27413f5f125d30c9d726684886c69a", GitTreeState:"clean", BuildDate:"2021-04-16T13:08:35Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

oc version
Client Version: 4.5.0-202005291417-9933eb9
Server Version: 4.7.9
Kubernetes Version: v1.20.0+7d0a2b2
```

**Comment by myan9** [comment]
Hi @haf-tech ! Can you give us a screenshot of any error in the JS dev console? Thanks!

**Comment by starpit** [comment]
I think we see the problem. We'll ping this thread when we release a fix.
