### ISSUE TITLE
kui not carrying over --kubeconfig option 

### ISSUE THREAD

**Issue by Jishun** [kubernetes-sigs/kui#7363]
When there is a --kubeconfig option specified, it's able to carry on in some cases but not for some others

**Steps to reproduce the behavior**

1. start a cli tab, type a command with kubeconfig option : `k get pods -n mynamespace --kubeconfig ~/.kube/prod` #a custom prod config file instead of the default
2. Pods a listed properly 
3. Click on one of the pod names
4. In right pane, pod description is displayed properly, the right pane initial command line has the proper --kubeconfig option
5. click on Logs tab in the right pane 
6. it's unable to retrieve the log and returns a strange error that appears caused by misunderstanding the kube config file option

**Expected behavior**
--kube config option carried on properly, and logs are retrieved.

**Screenshots**
![image](https://user-images.githubusercontent.com/12438914/116800808-af7a7d00-ab47-11eb-9010-dbe001dff755.png)

- Kui version: 10.3.0
- Operating system: windows

**Comment by starpit** [comment]
Hello, and thanks so much for the bug report! Appreciated. We'll check it out.

**Comment by zgfh** [comment]
if there is a way to set context like 'iterm profile',it will easy to use

**Comment by starpit** [comment]
Triage: My guess is that `plugins/plugin-kubectl/logs/src/controller/kubectl/logs.ts` is not expanding the `~`
