### ISSUE TITLE
Cannot get ingress

### ISSUE THREAD

**Issue by kevmando** [kubernetes-sigs/kui#7387]
**Describe the bug**
Existing ingress is not returning and give the following error.

```
kubectl get ingress --all-namespaces
error: the server doesn't have a resource type "Ingress"
```

**Steps to reproduce the behavior**
Open Kui
Run `kubectl get ingress --all-namespaces` where cluster has any ingress.

**Expected behavior**
Returned existing ingress. 
(Ingress returns with other terminal apps such as iterm2, but not kui.)

**System**

- Kui version: 10.1.4
- Operating system: OS X 11.2.3

**Comment by starpit** [comment]
Howdy, thanks for the bug report. We will look into this tomorrow or the next day hopefully!

**Comment by starpit** [comment]
More findings:

this seems to correctly assess the existence of the kind, in kui:
```sh
kubectl explain ingress
```

but the suggested `k get ingress` errors at, as specified in the issue.

**Comment by myan9** [comment]
I think #7383, #7302 and #7301 have the same problem. The resource kinds end with 's' but are not plural. PR #7415 fixed this issue by using a real plural npm.

**Comment by starpit** [comment]
wow, nice catch!

**Comment by kevmando** [comment]
wow, fast. thank you.

**Comment by starpit** [comment]
Thanks for identifying the bug! We should have a 10.3.x set of prebuilt binaries out within the next few days.
