### ISSUE TITLE
Kui appears to look for invalid filenames in Windows

### ISSUE THREAD

**Issue by mlthorne** [kubernetes-sigs/kui#7405]
-Open Kui
- Create simple notebook (k get ns)
- File -> Save as new Notebook -> enter filename and save
- Close Kui and Reopen
- File -> Open -> Choose file -> Press "Open" button
- No visible output in app, error visible in --enable-logging or ProcMon

(screenshots of errors in both attached)

From watching app behavior in ProcMon, it seems to be calling a file whose name is the concatted file path to that file as part of the name, so if I try to open 
c:\users\username\desktop\kui\kuitest7.kui 
it is looking for 
c:\users\username\desktop\kui\usersusernamedesktopkuitest7.kui

**System Info**

- Kui version: 10.2.1
- Operating system: 
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
(seen in other Win 10 environments as well, but cannot replicate in MacOS current version)
![SNAG- 5-17-2021 001](https://user-images.githubusercontent.com/5209979/118507191-01043980-b6fc-11eb-98d0-e7a795516d37.png)
![SNAG- 5-17-2021 003](https://user-images.githubusercontent.com/5209979/118507196-02cdfd00-b6fc-11eb-8664-5e6642a8e17d.png)

FWIW, it could be something completely different that is keeping me from using Save\Open, but this is at least my best guess at what is causing the issue. Happy to provide additional information as needed.

**Comment by starpit** [comment]
Howdy, thanks for the bug report! We will look into this tomorrow or the next day, hopefully!

**Comment by myan9** [comment]
Thanks @mlthorne ! Can I double-check that you were running on Win32?

**Comment by starpit** [comment]
It looks like there are two bugs in Kui:

1. File->Save does not properly handle backslash paths
2. the `replay` command also does not properly handle backslash paths

Oddly, the `snapshot` command *does* support these paths.
