### ISSUE TITLE
pipeStages splits command with >> incorrectly

### ISSUE THREAD

**Issue by myan9** [kubernetes-sigs/kui#7413]
For commands that have >>, splitIntoPipeStages splits the command as redirecting to a file with prefix '> '
![Screen Shot 2021-05-18 at 1 07 16 PM](https://user-images.githubusercontent.com/21212160/118694335-f9b35d80-b7d9-11eb-8334-eea1198fdc9f.png)

**Comment by starpit** [comment]
>
>>
>&
2>

**Comment by starpit** [comment]
@myan9 suggests that at the very least, we can just not parse `>>` as a redirect in the pipe stage parser

**Comment by starpit** [comment]
I suggest we split this into two pieces: one is the parsing issue. Second, in repl/exec, we always use `vfs fwrite` even if the redirect is an append, e.g. `>>`. The latter will require some updates to the fwrite api, so I suggest we handle that separately.
