### ISSUE TITLE
update checker does not ignore empty github releases

### ISSUE THREAD

**Issue by starpit** [kubernetes-sigs/kui#7438]
Sometimes, perhaps briefly, we may have github releases with no downloads, and even no message. But Kui will offer this as an available update to users.

**Comment by myan9** [comment]
Maybe we should get the latest release via Github API, as it will return the most recent non-prerelease and non-draft release, and it should be the same latest release shown in Kui's Releases page. Currently we list all releases via https://github.com/kubernetes-sigs/kui/releases.atom, which doesn't contain assets and those filters above, so we had to put a lot of logic to check which release is the latest.
