### ISSUE TITLE
Failed to build docker image with wiki guide on linux (Field 'browser' doesn't contain a valid alias configuration)

### ISSUE THREAD

**Issue by xiaoshimimi** [kubernetes-sigs/kui#7640]
**Describe the bug**
I'm trying to build kui docker image with this guide: https://github.com/kubernetes-sigs/kui/wiki/4.-Building-for-Production#scripts-to-aid-in-building-a-hosted-kui

But failed finally with some error.

**Steps to reproduce the behavior**

1. `git clone git://github.com/IBM/kui.git`
2. `cd kui`
3. `npm ci`
4. `INJECT_KUBECONFIG=true npx kui-build-docker-with-proxy`
5. see error:

![image](https://user-images.githubusercontent.com/5269532/122166257-edd7bb80-ceab-11eb-9e96-35e9a6839279.png)

**Expected behavior**
does not get error with `npx kui-build-docker-with-proxy` command

**System**

- Kui version: `master branch`
- Operating system: `Red Hat Enterprise Linux release 8.3 (Ootpa)`

**Comment by starpit** [comment]
As with #7639, I am going to assume that this observed error is a side-effect of an underlying regression that broken this build path. Let me know if that is not the case, once #7641 is merged.
