### ISSUE TITLE
Kui should offer a client option to show the block execution buttons sequentially

### ISSUE THREAD

**Issue by myan9** [kubernetes-sigs/kui#7659]
The execution buttons for blocks should be sequential. Only if the previous block had been executed successfully, the button in the next block should become available, and the button in the previous block should get disabled.

**Comment by starpit** [comment]
I think this issue is not referring to a general property of Kui, rather that Kui could support such a mode. This kind of step-at-a-time feature could be useful for educational/onboarding notebooks.
