### ISSUE TITLE
Custom client has product name acting as a link that does nothing

### ISSUE THREAD

**Issue by mark-nc** [kubernetes-sigs/kui#7709]
**Describe the bug**
In our custom client we have assigned the product title which is displayed in the top tab stripe to the left of the "Tab 1".  The appearance of the text is fine, but if the user moves the mouse pointer over it, the cursor changes to the "finger" and it highlights like a link.  Examining the DOM shows that it is wrapped in an `<a>` tag, hence getting that behavior. 

**Steps to reproduce the behavior**

1. Hover over product title in the top tab stripe.

**Expected behavior**
The text is just text, not a link.

**System**

- Kui version: 10.3.z
- Operating system: Red Hat ubi container at RHEL-8

**Comment by starpit** [comment]
This comes from the <PageHeader> instance. We are using the default `logoComponent` which is indeed `a`, but we also set no `logoProps`, which means that the anchor has no `href`. So, sane CSS rules would give no hover effect. And indeed this is the case for stock Kui. But perhaps other CSS rules may change this behavior?

We can change the `logoComponent` to `span` to help this out.
