### ISSUE TITLE
Tab close icon tooltip shows shortcut key that does not work

### ISSUE THREAD

**Issue by mark-nc** [kubernetes-sigs/kui#7786]
**Describe the bug**
The close tab icon has a hover tooltip that says `Close this tab ^W`, but no key combo including `W` will close the tab so that is confusing.  Also, use of `^` as a key modifier may not be commonly known to users of different OSes when running the client in a browser.  The `^W` should probably be removed from that tooltip text.

**Steps to reproduce the behavior**

1. Go to Kui UI in a browser client
2. Open a second tab
3. Hover over the tab close icon on either of the two tabs
4. Observe the tooltip hover text

**Expected behavior**
Removal of the `^W` if a keyboard shortcut does not really work in a browser client.

**Screenshots**
![image](https://user-images.githubusercontent.com/51764173/125107863-4a935400-e0af-11eb-8785-79b136a53560.png)

**Code snippets**
N/A

**System**

- Kui version: 10.3.27
- Operating system: MacOS in this case using Chrome browser

**Comment by starpit** [comment]
Probably a bug with the webpack browser shims for `process.platform`?
