### ISSUE TITLE
Using export with a subshell command to get dockerconfig does not work

### ISSUE THREAD

**Issue by mark-nc** [kubernetes-sigs/kui#7791]
**Describe the bug**
Trying to assign a pull secret JSON to `DOCKER_CONFIG_JSON` using a subshell command does not work when the namespace parameter is specified.

**Steps to reproduce the behavior**

1. Enter an `oc` command to return the dockerconfig JSON for a pull secret, e.g., `oc extract secret/multiclusterhub-operator-pull-secret -n open-cluster-management --to=-`
2. Notice that it returns the `.dockerconfigjson`
3. Enter the same command, but assign it to an exported variable, e.g., `export DOCKER_CONFIG_JSON=$(oc extract secret/multiclusterhub-operator-pull-secret -n open-cluster-management --to=-)`
4. See error `Unsupported optional parameter -n`

_Note: step 3 above uses the `$( )` notation for the subshell command as that is now POSIX standard across all shells (the old syntax of using back ticks is deprecated)._

**Expected behavior**
There should be no error and the returned JSON seen in step 2 should be assigned to `DOCKER_CONFIG_JSON`

**Screenshots**
Not showing screenshots as no need to show a private pull secret.

**Code snippets**
N/A

**System**

- Kui version: 10.3.27
- Operating system: custom Kui browser client running in Chrome on MacOS

**Comment by starpit** [comment]
The `export` command currently assumes `echo -n` works.

**Comment by mark-nc** [comment]
Steps 1-3 work on a normal terminal window and that is why this issue was opened against our custom Kui client by one of our users.  If the subshell command is a k8s command that takes the `-n` namespace parameter, that should be processed in context of that command and not the export command itself.

**Comment by starpit** [comment]
Does your proxy support `echo -n`?

**Comment by mark-nc** [comment]
If you mean does `echo -n $exportedVariable` on the Kui command line return the value of `exportedVariable`, yes.

**Comment by starpit** [comment]
Ok, then the error must be coming from `oc` itself.

**Comment by starpit** [comment]
Nope, this error comes from the `export` command expecting strict enforcement of options.

**Comment by mark-nc** [comment]
My Macbook currently uses zsh instead of bash, but in zsh that same export command does not emit any error and the command works.

**Comment by starpit** [comment]
i already opened a PR for this.
