### ISSUE TITLE
replay snapshot get error

### ISSUE THREAD

**Issue by yuecchen** [kubernetes-sigs/kui#7866]
**Describe the bug**
replay snapshot get error

**Steps to reproduce the behavior**

1. Launch a KUI
2. run some command
3. run `snapshot /tmp/ss1`
4. run `snapshot /tmp/ss2`
5. run `snapshot /tmp/ss1`
6. run `replay /tmp/ss1`
7. got error
```
Unexpected end of JSON input
```

**Expected behavior**
replay previous command

**Screenshots**
<img width="1083" alt="Screen Shot 2021-08-13 at 11 47 40 AM" src="https://user-images.githubusercontent.com/24837518/129302700-3999550e-d064-49c4-a6f3-93f8461a23ec.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version: `latest master code`
- Operating system: `x86 redhat`

**Comment by starpit** [comment]
Hey! I'm so sorry that this one slipped through the cracks. Could you either send me the snapshots, or try again with the latest? Some bugs have been fixed in this area.
