### ISSUE TITLE
Is there any general purpose framework can build hybrid command line and GUI app like KUI

### ISSUE THREAD

**Issue by link89** [kubernetes-sigs/kui#7867]
The idea of kui is awesome and I am just wondering is there any general purpose UI framework that can build the tools like kui does.

**Comment by starpit** [comment]
Howdy! Can you help me to understand better what you are suggesting? Kui has a plugin model, and so in a way *is* such a framework. But I think you are asking something different? Thanks!

**Comment by link89** [comment]
Yeah. I think what makes KUI great is its UX design that it combines the best qualities of both command line and GUI. What I want to know is there any general purpose framework that allow me to build web app with similar experience of KUI.

**Comment by kferrone** [comment]
KUI is a terminal app based on Electron. 
So here is a framework for building terminal apps with Electron:  https://hyper.is/
Also this one too: https://www.electronjs.org/apps/extraterm
And this one: https://github.com/mflorence99/el-term
Oh and this one too: https://xtermjs.org/

**Comment by starpit** [comment]
@link89 I'm still not sure what you are after. Kui has a set of APIs that let you consume Kui's core features as npm modules (e.g. `npm install @kui-shell/core`). You may then extend Kui, by adding custom commands (e.g. to enhance your own CLI), or by customizing the theming (e.g. to use a custom app icon, custom colors, custom application name).

An example of doing this is in the "AnimalApp" app located [here](https://github.com/kubernetes-sigs/kui/tree/master/docs/example/AnimalApp).

**Comment by starpit** [comment]
The Kui [wiki](https://github.com/kubernetes-sigs/kui/wiki) has additional detail on creating custom Kui clients.

**Comment by starpit** [comment]
As to @kferrone's comment. These are all great projects! The goal of Kui is to provide graphical enhancement to the command execution model of terminals. So, with Kui you may "attach" command handlers to the read-eval-print loop of the terminal, and instead of presenting ASCII responses, you may do ... other things, such as provide arbitrary React responses, or table responses or tabular/multi-tab responses, etc.

**Comment by starpit** [comment]
We have externalized the example client into a github template repo: https://github.com/kui-shell/KuiClientTemplate
