### ISSUE TITLE
`kubectl delete pod` returns `404 page not found` but works from terminal

### ISSUE THREAD

**Issue by jsolbrig** [kubernetes-sigs/kui#8004]
**Describe the bug**

I'm just getting started test driving Kui and really like it so far. I'm likely doing something wrong or have something misconfigured.

When attempting to delete a pod via Kui with `kubectl delete pod -n testing nginx` I get `404 page not found`. The same command works as expected from the terminal.

I'm seeing this issue with other pods too, not just this specific pod or namespace.

**Expected behavior**
`kubectl delete pod -n testing nginx` should delete the `nginx` pod from the `testing` namespace.

**Screenshots**
![image](https://user-images.githubusercontent.com/1684491/133500754-3afdf96d-b0fc-4135-bbf7-a974dff16902.png)

**System**

- Kui version: I'm actually not sure where to find this. `Menu Bar -> Kui -> About Kui` takes me to the Getting Started page.
- Operating system: macOS Catalina 10.15.7

**Comment by starpit** [comment]
Thanks for the bug report. Is the Kube proxy configured in your cluster? Kui should work in either case, but I think I see a small bug in the error handling in the proxy case (Kui falls through to the non-proxy case).

**Comment by jsolbrig** [comment]
I'm using RKE to stand up my cluster which appears to always create `kube-proxy`. See the very bottom of this page: https://rancher.com/docs/rke/latest/en/config-options/services/#kubernetes-network-proxy

**Comment by starpit** [comment]
Interesting, thanks. The 404 is a good sign that something isn't right with the kube-proxy. But off the top of my head, I'm not sure what... I have a PR to improve the error handling. #8005

**Comment by jsolbrig** [comment]
Okay, thanks. Is there anything that I can do on my end to help debug?

**Comment by starpit** [comment]
It could be something rancher-specific. The PR should get you past this, at least for now. I'll open up a separate issue to explore using the API for multi-cluster providers. https://github.com/rancher/rancher/issues/16138

**Comment by jsolbrig** [comment]
Okay, thanks, I'll give the PR a shot shortly. Thanks for the help and the PR!
