### ISSUE TITLE
Allow using non-bash shells

### ISSUE THREAD

**Issue by nmiculinic** [kubernetes-sigs/kui#8205]
I'm using zsh which has all my kubectl aliases, but kui uses bash by default. Couldn't find any setting to swith the shell

**Comment by khuedoan** [comment]
/remove-lifecycle stale

I'm having this issue as well (version `0.4.31_Linux_amd64`):

![image](https://user-images.githubusercontent.com/27996771/150835643-372c52eb-36a9-43fe-94ec-e49f7e1f7d66.png)

**Comment by starpit** [comment]
Thanks for the update 👍
