### ISSUE TITLE
kubectl hangs on almost any command that should return cluster info

### ISSUE THREAD

**Issue by horihel** [kubernetes-sigs/kui#8211]
**Describe the bug**
first time KUI user here - any command involving kubectl getting info (or outputting it) just hangs with the indicator showing that it's "working". Looking at the process list shows that kui started a kubectl process, it seems to exit, but kui still reports it as "running".

I suspect user error or something peculiar with my installation, but cannot find the cause.

`kubectl config` commands work, as do some unformatted outputs (like `kubectl version`).
helm works

unfortunately i couldn't find a way how to enable verbose logging or debug output.

**Steps to reproduce the behavior**

1. run kubectl version - works
2. kubectl get pods -> infinite spinner
3. also mentioning that the namespace indicator on the bottom is "Loading" very long.

**Expected behavior**
kubectl pods outputting ... something.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6735079/138041546-afd666fb-aabc-4153-b4dc-27ac41a4d6b2.png)

Also worth mentioning that prereq --module Kubernetes shows red for kubectl, but no explanation as to why.
![grafik](https://user-images.githubusercontent.com/6735079/138041703-57c38167-cb91-42cf-b0fe-a3611860a247.png)

"up" shows all good.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version: probably 10.8.1 (about screen does not show a version number) - via chocolatey
- Operating system: Windows 10 20h0
- kubectl 1.22 via chocolatey
- helm 3.7.0 via chocolatey

**Comment by asafwat** [comment]
I faced the same problem and restarting windows fixed for me, for now.

**Comment by ssmall** [comment]
I am experiencing the same behavior. Kui worked the first time I used it after install, but after quitting the first session it has not worked again.

**Comment by horihel** [comment]
Found a bit of detail:
turns out this happens only on specific clusters (especially those managed through rancher).

Kui spawns a "kubectl proxy" process on start, listening and forwarding port 8001. This process has several problems:
- It is not killed when Kui exits - it stays around and will block port 8001 - later invocations of Kui cannot spawn another kubectl process and might run up in the wrong context, but usually will just hang. It's possible that this only affects Windows.
- It is not killed/replaced if you switch contexts. This results in a guaranteed hang of all kubectl commands if you switch contexts in Kui.
- It does not work properly when connecting to rancher. It never shows the target context - instead it shows resources from Rancher's management cluster.
