### ISSUE TITLE
Rename tabs

### ISSUE THREAD

**Issue by kdeyko** [kubernetes-sigs/kui#8251]
Hi there!

It'd be nice to be able to rename tabs, so they are not just "Tab 1", "Tab 2", etc., but having a meaningful names like "Dev", "QA", "Prod", "whatever".

Thanks!

**Comment by starpit** [comment]
Great idea, thanks!

**Comment by bitsofinfo** [comment]
Please add this feature!

**Comment by starpit** [comment]
👍 Thanks for the ping!

**Comment by starpit** [comment]
https://github.com/kubernetes-sigs/kui/pull/8857 will do this in an ephemeral way: renames will not survive restarts nor transfer to other windows. Ping this thread if future readers need more durability.

**Comment by starpit** [comment]
11.5.0 has been released!
