### ISSUE TITLE
Mention kui within https://kubernetes.io/docs/

### ISSUE THREAD

**Issue by sftim** [kubernetes-sigs/kui#8267]
Just that really. Add an item to an existing page within https://kubernetes.io/docs/ that mentions kui.

For example, add it to https://kubernetes.io/docs/reference/tools/

**Comment by sftim** [comment]
(if accepting this suggestion, consider transferring the issue to [k/website](https://github.com/kubernetes/website) with the Prow command `/transfer website`)

**Comment by starpit** [comment]
Hi Tim, great idea. Thanks for catching this gap!

/transfer website

**Comment by sftim** [comment]
Ah, we can't transfer between kubernetes-sigs and kubernetes.

**Comment by sftim** [comment]
Done in https://github.com/kubernetes/website/pull/30598

/close

**Comment by starpit** [comment]
thanks so much @sftim !
