### ISSUE TITLE
Will not run on Windows 11 + WSL-G

### ISSUE THREAD

**Issue by BryanDollery** [kubernetes-sigs/kui#8279]
I'm trying to run Kui in Windows 11 with WSL-G (ubuntu 20.04). 

I've confirmed that my wsl-g works by successfully running gimp and other graphical linux apps.

I have installed Kui (`Kui-linux-x64.zip`) from the github releases page, v10.8.2 (https://github.com/kubernetes-sigs/kui/releases/tag/v10.8.2), unzipped it into /usr/local/bin and added `:/usr/local/bin/Kui-linux-x64` to my path. 

But when I run
```bash
kubectl kui
```
or even just:
```bash
Kui
```
The response I get is:
```bash
/usr/local/bin/Kui-linux-x64/Kui: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by starpit** [comment]
Howdy! Thanks for reporting this. There are probably some missing X-related dependencies that the underlying chromium relies on. Could you try

```
sudo apt install libatk-bridge2.0-0 libgtk-3.0
```

There may be a few others, but ... crossing fingers that should cover it?

It has been a TODO for a while to get a `.deb` package built for Kui. I think that would avoid this dependence issue, at least for debian-related linux.

**Comment by starpit** [comment]
You may run into another issue, reported a while back: https://github.com/kubernetes-sigs/kui/issues/5110

> The futex facility returned an unexpected error code.Aborted

Let us know if you see that!

**Comment by BryanDollery** [comment]
```bash
sudo apt install -y libatk-bridge2.0-0 libgtk-3.0

E: Unable to locate package libgtk-3.0
E: Couldn't find any package by glob 'libgtk-3.0'
```

The libatk-bridge partially installs as a separate thing, but I get an error too:

```bash
sudo apt install -y libatk-bridge2.0-0

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core libatspi2.0-0
The following NEW packages will be installed:
  at-spi2-core libatk-bridge2.0-0 libatspi2.0-0
0 upgraded, 3 newly installed, 0 to remove and 89 not upgraded.
Need to get 171 kB of archives.
After this operation, 783 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libatspi2.0-0 amd64 2.36.0-2 [64.2 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 at-spi2-core amd64 2.36.0-2 [48.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libatk-bridge2.0-0 amd64 2.34.2-0ubuntu2~20.04.1 [58.2 kB]
Fetched 171 kB in 2s (96.4 kB/s)
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 59326 files and directories currently installed.)
Preparing to unpack .../libatspi2.0-0_2.36.0-2_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.36.0-2) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../at-spi2-core_2.36.0-2_amd64.deb ...
Unpacking at-spi2-core (2.36.0-2) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../libatk-bridge2.0-0_2.34.2-0ubuntu2~20.04.1_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.34.2-0ubuntu2~20.04.1) ...
Setting up libatspi2.0-0:amd64 (2.36.0-2) ...
Setting up libatk-bridge2.0-0:amd64 (2.34.2-0ubuntu2~20.04.1) ...
Setting up at-spi2-core (2.36.0-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
/sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link
```

**Comment by BryanDollery** [comment]
Any more advice on this one? I'd really like to get it working.

**Comment by marco-gallinari** [comment]
I managed to start kui on w11 + WSL2 (ubuntu 20.04) with these packages:

    sudo apt-get install -y libatk-bridge2.0-0  libgdk-pixbuf2.0-0  libgtk-3-0 libgbm1
 
only thing is, if I resize the window Kui freezes

**Comment by marco-gallinari** [comment]
errata corrige: if I just run kubectl kui, without any command, I can resize the window correctly and run kubectl commands inside kui.
