### ISSUE TITLE
Remove need to have 'kubectl' before each command

### ISSUE THREAD

**Issue by BryanDollery** [kubernetes-sigs/kui#8309]
As this tool is designed to run kubectl, why should I have to type kubectl at the start of every command? I mean, I understand why that's necessary in the current implementation, but maybe that should change? I don't need to be able to execute arbitrary commands from this tool -- I have a very capable bash terminal that I can use for that. Maybe this tool could focus on its core mission and make it easier to use just kubectl.

**Comment by starpit** [comment]
Howdy, thanks for the feedback! I agree this would be helpful. There is a feature that we could polish off to make it happen. For now, there is the `k` shortcut in Kui which can help to reduce the amount of needless typing! e.g.

```bash
k get pods
```
