### ISSUE TITLE
Remove the tooltip style brightness filter

### ISSUE THREAD

**Issue by bopohaa** [kubernetes-sigs/kui#8318]
This style `plugins/plugin-client-common/web/scss/components/Tooltip/PatternFly.scss` (line: 68) contains brightness filter
In dark themes, this style makes the text unreadable. 
Thanks.

**Comment by starpit** [comment]
Howdy, thanks for the bug report! To help with tracking this, could you attach a screenshot at your convenience? Thanks!

**Comment by bopohaa** [comment]
Hello. On my win10 kui looks like this:
![image](https://user-images.githubusercontent.com/1828338/147107970-14915142-b2d6-44d6-a56a-b54743ece110.png)

**Comment by starpit** [comment]
Thanks! 👍

**Comment by bopohaa** [comment]
Thank you. Looks good, but there is still a small "problem" in displaying the tooltip on a button with a question mark 
![image](https://user-images.githubusercontent.com/1828338/147237148-2c46956b-e785-45a8-938d-692ccb33b5b3.png)
