### ISSUE TITLE
enhancement: "lock" action context for rapid dev/debug cycle

### ISSUE THREAD

**Issue by rabbah** [kubernetes-sigs/kui#841]
i'm trying to write a function entirely using the editor and the shell (using webpacked) mode.
in this case, i edit my function, click deploy ("save") and then want to run. 

in split mode, i can type `invoke my-action-name` to invoke my action, then click the action name to "get" the action and then "unlock" the action to resume editing.

clicking the action name causes "get" command to appear on the prompt so that now i lost my invoke command (ie this requires scrolling up my history to run again - up arrow, up arrow, enter)

so i'm opening this issue for discussion as there may be a way to save a few clicks and making running my function in the cloud as convenient as running "node f.js" locally --- so i can test entirely in the cloud.

in particular, some obvious things:
1. maybe clicking the action name could omit the "wsk action get ..."; i see the value in that in general but not in this case
2. retain the function name so that i can just type invoke without the name of the function
3. having an "open function for editing" button in the lower nav bar of the action result would save from mousing up and clicking the action name and then mousing all the way back down to unlock the action

**Comment by starpit** [comment]
nice suggestions. could tabs help here possibly?
