### ISSUE TITLE
Add support for hyperlinks with {target=...} in markdown

### ISSUE THREAD

**Issue by mra-ruiz** [kubernetes-sigs/kui#8432]
**Describe the bug**
Hyperlinks in markdown format are not rendering correctly.

**Steps to reproduce the behavior**

1. Edit your markdown file
2. Try to include a hyperlink
3. See error

**Expected behavior**
The hyperlink should render by having a different font color for the hyperlinked text, as well as including a grey box surrounding the hyperlinked text.

**Code snippets**
Example of how hyperlinking in markdown should look:
```
[`text to be linked`](https://github.com){target=\_blank}
```
What it ends up looking like:
[text to be linked](https://github.com){target=\_blank}

**System**

- Kui version: 10.8.0
- Operating system: macOS Monterey Version 12.1

**Comment by starpit** [comment]
It might be worth clarifying that only *some* and only non-standard hyperlinks (the pymdown `{target...}` extensions) aren't rendering properly.
