### ISSUE TITLE
any kubectl command hangs (Windows?)

### ISSUE THREAD

**Issue by frostmar** [kubernetes-sigs/kui#8662]
**Describe the bug**
Any `kubectl` command hangs, with a blinking blue square animation but no output is ever produced.
That includes trivial commands such as `kubectl version`

Non-kubectl commands eg `ls` output OK.

Unlike https://github.com/kubernetes-sigs/kui/issues/8211 even `kubectl config` does not work.

**Steps to reproduce the behavior**

1. launch kui.exe 
2. run any kubectl command eg `kubectl version`

**Expected behavior**
Normal output

**Screenshots**
hanging:
![image](https://user-images.githubusercontent.com/3381992/154460624-c21fe87f-4d33-4a42-ba1f-4686a4b7b8c6.png)

Windows task manager shows one child process not responding:
![image](https://user-images.githubusercontent.com/3381992/154461083-e7e0f141-9138-4569-81a2-e1d09e2e30fc.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version: 11.2.5 (downloaded Kui-win32-x64.zip, unpacked, run kui.exe)
- Operating system: Windows 10 Enterprise 21H1

**Comment by starpit** [comment]
Thanks for the report! To help debug this, can you let us know how you launched Kui? From a double click, from powershell, from git bash, or?

Thanks!

**Comment by frostmar** [comment]
I was launching `kui.exe` by double-click from Explorer

Checking now, running from commandline (cmd or gitbash) gives the same behaviour

**Comment by starpit** [comment]
Thanks! I think if you back off to [Kui 10.8.2](https://github.com/kubernetes-sigs/kui/releases/tag/v10.8.2), it may work better on Windows? We'll look into issues with the latest builds.

**Comment by frostmar** [comment]
Thanks for the tip - v10.8.2 works OK for me (Windows 10 Enterprise 21H1)

**Comment by starpit** [comment]
Awesome, thanks so much for identifying this bad bug. We will update the latest release notes to point windows users to 10.8.2 until this is resolved.

**Comment by starpit** [comment]
Not sure why yet, but for some reason the `node-pty` module is hanging when it tries to connect to the `conpty` process that it itself spawned. I've [asked the node-pty devs](https://github.com/microsoft/node-pty/issues/532) to see if they have any insight.
