### ISSUE TITLE
Opening terminal kills kui 10.2 (on Windows)

### ISSUE THREAD

**Issue by pedu1** [kubernetes-sigs/kui#8700]
When opening pod info and trying to enter the Terminal It just hangs forever with text "Please wait. Connecting to container X". Earlier this was working just fine.

**Comment by starpit** [comment]
Thanks for the report! This may be related to #8662.

It is possible that the PTY native modules do not function correctly with recent builds. To help debug this, can you let me know your version of Windows, and whether you launched Kui from a double click, from powershell, from git bash, or?

Thanks!

**Comment by pedu1** [comment]
Hi, 

Windows version is:
Edition	Windows 10 Pro
Version	21H1
Installed on	‎31.‎5.‎2020
OS build	19043.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

I did launch Kui from taskbar where it's pinned. Same result by double clicking the .exe as well (just tried).

**Comment by starpit** [comment]
Thanks! I think if you back off to [Kui 10.8.2](https://github.com/kubernetes-sigs/kui/releases/tag/v10.8.2), it may work better on Windows? We'll look into issues with the latest builds.
