### ISSUE TITLE
Starting kui only shows blank window

### ISSUE THREAD

**Issue by horihel** [kubernetes-sigs/kui#8704]
**Describe the bug**
On Windows, installation is from chocolatey.

See screenshot:
![grafik](https://user-images.githubusercontent.com/6735079/155673594-4a966313-62c6-4712-ad47-c1974e7d05e8.png)

Most actions (like new tab) do nothing. New window opens an identical window. Opening console shows this:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getCurrentWindow')
    at Module.<anonymous> (electron.9653956ed64020480b29.bundle.js:1)
    at Generator.next (<anonymous>)
    at s (electron.9653956ed64020480b29.bundle.js:1)
```

Already tried clearing out %APPDATA%/kui-shell, didn't change a thing.

**Steps to reproduce the behavior**

1. Be on my machine
2. launch kui directly
3. See error

**Expected behavior**

**System**

- Kui version: 11.4.0 - installed via chocolatey
- Operating system: Windows 10 21H2

**Comment by horihel** [comment]
looks like the chocolatey package is broken - uninstalling that and using 11.4.0 directly from the .zip file works.

**Comment by starpit** [comment]
Interesting! We have not yet (ever) published a chocolatey package. We'll look into the origin story here. Thanks for the heads up.
