### ISSUE TITLE
Error: flags cannot be placed before plugin name: --allow-file-access-from-files

### ISSUE THREAD

**Issue by dargenn** [kubernetes-sigs/kui#8746]
**Describe the bug**
Error message after trying to list the pods.
`Error: flags cannot be placed before plugin name: --allow-file-access-from-files`
I've just installed kui and it was the first thing I've tried to do, does not appear to be working.

**Steps to reproduce the behavior**

1. brew install kui
2. kubectl kui get pods

**Expected behavior**
Listed pods.

**Screenshots**
![image](https://user-images.githubusercontent.com/12902892/157890856-820834c4-61dd-46a6-a325-96360aab7ba4.png)

**System**

- Kui version: 11.4.0
- Operating system:
```
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```

**Comment by starpit** [comment]
Howdy! Thanks for the bug report. I can reproduce this bug when opening up a second window. It does not seem to fail in this way for a "french launch" (i.e. if the Kui process is not already active). Investigating...

**Comment by starpit** [comment]
Reopening: we missed a flag that seems to be linux-specific.

**Comment by starpit** [comment]
Hopefully 11.4.4 (`brew upgrade kui` for macos users) should fix this.

Future readers: Please ping here if you see other forms of this error. We weren't sure how to resolve this definitively (chrome began to smash in random command line arguments, but without a clear and easily filterable --chrome-... prefix...)
