### ISSUE TITLE
Can't save the guidebook. Nothing happens

### ISSUE THREAD

**Issue by nikmel2803** [kubernetes-sigs/kui#8889]
**Describe the bug**
I can't save guidebook. When I click on "Save as guidebook" button nothing happens (the same behavior if I try to click cmd + s).
There are no errors in the logs either.

<img width="208" alt="image" src="https://user-images.githubusercontent.com/32655339/172994137-9e823ea6-5b3e-412a-94aa-77c2be5c579c.png">

**Steps to reproduce the behavior**

1. Create new Tab
2. Write some commands
3. Click File -> Save as guidebook
4. Nothing happens

**Expected behavior**
A new window will appear to save the file.

**System**

- Kui version: 11.5.0
- Operating system: 

<img width="213" alt="image" src="https://user-images.githubusercontent.com/32655339/172993924-2384c35c-6366-46c5-8d7a-37dcd29d49e7.png">

**Comment by starpit** [comment]
howdy, and thanks for the bug report!

In Kui 11, notebooks are now sourced from markdown. It slipped through the cracks (doh!) to remove the Save button from the UI, and to better document this transition.

Here are some examples of the source material. These back the notebooks that ship with Kui: https://github.com/kubernetes-sigs/kui/tree/master/plugins/plugin-client-common/notebooks

**Comment by nikmel2803** [comment]
@starpit thank you for the reply
i.e. I can't edit my laptops through the app (like WYSIWYG)? Only through markdown directly?

**Comment by starpit** [comment]
You can use the "Guidebook Playground" notebook, which does have a live preview mode. You would then have to copy/paste the text out when you're ready to save it. Adding a save button to the playground dashboard would be a neat feature to add! As would updating the `replay` command (`replay /path/to/my.md`) to have a `--watch` option, so that it watches the file for changes.

PRs welcome! 🙇

**Comment by starpit** [comment]
https://user-images.githubusercontent.com/4741620/174303021-2e8e4663-1143-40ff-834a-99f7cd08f5a4.mp4
