### ISSUE TITLE
Clarify how to install in Linux

### ISSUE THREAD

**Issue by rinormaloku** [kubernetes-sigs/kui#8916]
The zip doesn't contain just a binary. It contains a ton of files.

Elaborate on how to properly install this tool. I don't want to throw in files that are difficult to clean up later on.

**Comment by starpit** [comment]
Howdy, thanks for the feedback, much appreciated! What you see in the zip file are the contents of an Electron application. You may notice that, for example, the [VSCode Linux tarball](https://code.visualstudio.com/sha/download?build=stable&os=linux-x64) has a quite similar structure (it also being an Electron app), with (in both cases) the bulk of the files being under the `resources` directory.

Btw, to contribute a `dpkg` or `rpm` packager, see [here](https://github.com/kubernetes-sigs/kui/blob/master/packages/builder/dist/electron/build.sh#L239-L246). There is a [helper package](https://www.npmjs.com/package/electron-installer-debian) that assists with some of the details. I think the main missing piece os a useful manifest.
