### ISSUE TITLE
Not parsing HTTPS_PROXY properly

### ISSUE THREAD

**Issue by GreenStage** [kubernetes-sigs/kui#8933]
**Describe the bug**
 All kubectl commands fail with : `getaddrinfo ENOTFOUND socks5` when running KUI with the HTTPS_PROXY env set to `socks5://127.0.0.1:6783`,

**Steps to reproduce the behavior**

1. Open windows Command Prompt
2. Run `SET HTTPS_PROXY=socks5://127.0.0.1:6783 && START Kui`
3. `kubectl get pods -n <namespace>`

**Expected behavior**
kubectl requests should go through the HTTPS_PROXY smoothly

**Screenshots**
![image](https://user-images.githubusercontent.com/11062001/178721424-4563aff1-99d2-4ca8-aa59-bfffd08874aa.png)

**System**

- Kui version: 11.5.0
- Operating system: Windows x64

**Comment by starpit** [comment]
thanks for the bug report! we'll check it out.

**Comment by starpit** [comment]
Sorry it took so long to get to this one. The fix will be included in the next release!

**Comment by starpit** [comment]
The fix has been released in 12.0.0. If the problem persists, ping here!

**Comment by drennalls** [comment]
I'm still seeing the same thing on 13.0.0
![image](https://user-images.githubusercontent.com/16076/215609164-c55fc55b-b277-4331-aadd-8a0e9fd29a43.png)
