### ISSUE TITLE
Kui hangs shortly after startup

### ISSUE THREAD

**Issue by NovemberZulu** [kubernetes-sigs/kui#9055]
**Describe the bug**
Kui hangs shortly after showing UI. Activity monitor shows 100% CPU use. This is a regression and/or broken config at my side, Kui used to work fine.

**Steps to reproduce the behavior**
Start Kui from either Spotlight search or CLI `kubectl-kui`

**Expected behavior**
Kui starts and runs normally

**System**

- Kui version: 12.0.3
- Operating system: macOS 12.5.1

**Comment by starpit** [comment]
thanks for the bug report! can you make sure to quit all open Kui processes (check the Dock for a Kui icon), and then:

```
DEBUG=* kubectl kui get pods 2> /tmp/kui.err
```

and attach that file here? also, if it works, could you try going to View -> Toggle Developer Tools, and see if there are any errors in the Consoel tab? if so, paste them here, too? thanks!

**Comment by NovemberZulu** [comment]
Thank you for getting back to me! I am on Intel. I wasn't able to go DevTools because I get the beachball of death and have to force quit Kui. I was able to see the result, though (no pods in `default` namespace)
[Here is the log](https://gist.github.com/NovemberZulu/9ecc5658a7d5bf321b3d599e48b6824f). FInal lines lines look fishy. Is there a way to check what was that failed connection?

**Comment by starpit** [comment]
thanks! do you see the tray menu? if so, does it have any content? does it indicate version 12.0.3? 

one more quick experiment, can you try is to disable this functionality altogether, via:

```
KUI_NO_TRAY_MENU=true kubectl kui get pods
```

**Comment by NovemberZulu** [comment]
I see tray menu, and is has reasonable content, and the version 12.0.3, even through the menu freezes as well.
![Screenshot 2022-09-09 at 19 50 19](https://user-images.githubusercontent.com/897004/189413819-7e4472bc-bc6d-422e-8a5e-b4c99fb9a62a.png)

`KUI_NO_TRAY_MENU=true kubectl kui get pods` works completely fine! No freezes, etc. I think we are getting closer to the root cause!

`KUI_HEADLESS=true kubectl kui get pods` briefly shows Kui icon in dock, and then it goes away.

**Comment by starpit** [comment]
excellent. so 1) you have a path now at least to use the latest version; and 2) yes, the bug seems to be in the tray menu logic. i'll add some more debugging hooks and do a code review. at the very least (i.e. short of us finding the bug), we will have more info if you want to try out the tray menu in the next build.

thanks again!

**Comment by starpit** [comment]
Oh, what version of kubectl do you have? 

```kubectl version```

**Comment by NovemberZulu** [comment]
kubectl is 1.25.0, and clusters are 1.23.8. Could it be related?

**Comment by starpit** [comment]
those seem fine. but i'll do manual testing with the combo.
