### ISSUE TITLE
kubeconfig env var not working

### ISSUE THREAD

**Issue by pwright** [kubernetes-sigs/kui#9098]
**Describe the bug**

I think i'm seeing a regression of #7759 
ie cannot set kubeconfig in a tab

**Steps to reproduce the behavior**

When I issue the following command in terminal all works fine, but in kui it reports 'unauthorized'

`export KUBECONFIG=~/.kube/config-west; k get pods`

**Expected behavior**

For the command `export KUBECONFIG=~/.kube/config-west; k get pods`

In a bash session I get
`No resources found in default namespace.`

In Kui I get:

`Error from server (Unauthorized): Unauthorized`

should be the same?

- Kui version: 12.12.0
- Operating system: fedora 36

**Comment by starpit** [comment]
heya! sorry for the delay in getting back to you on this and your other questions. hopefully i'll have unwound some pressing matters that have come up in the next day or two, and i'll be back!

**Comment by pwright** [comment]
@starpit thx, no pressure
