### ISSUE TITLE
How to Load Bash Profile in Mac

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/kui#9151]
**Describe the topic**
I have installed KUI on MacM1 using Brew. When I launch KUI, I notice that nothing from `.bashrc`, `.bash_profile`, nor `.profile` is loaded in the context. Therefore all my helper scripts are unavailable, no variables either. If I try something like `source ~/.bash_profile`, still nothing??? 

What I did to kind of get it to work right; from a terminal simply run `/Applications/Kui.app/Contents/MacOS/kui`. This launches KUI using the terminal context instead. However, I still can't use any of my aliases nor variables from any profile. 

**Your suggestions for this topic**
Run KUI using the normal terminal profile so my setup just works in KUI.

**Comment by starpit** [comment]
Hello there, thanks for the feedback!

macOS treats launches from the dock or finder (e.g. double clicks) a bit specially: it does not run them through a normal login shell. Kui has some hacks in place that attempt to work around this, however they are limited to environment variables at the moment.

Regardless, it sounds like even those aren't working! If you could open up the dev tools (View -> Toggle Developer Tools), and then in the Console, if you filter by `prefetch`, you may see messages like:

> plugins/bash-like/pty/prefetch prefetchEnv +0ms
> plugins/bash-like/pty/prefetch skipping prefetchHome +0ms
> plugins/bash-like/pty/prefetch prefetchEnv got shell +15ms /bin/bash
> plugins/bash-like/pty/prefetch got env +102ms Object
> plugins/bash-like/preload done with state prefetch +135ms

or, if this logic fails, you will see mentions of errors. Do you see any of this? 

Thanks!
