### ISSUE TITLE
Logs doesn't show up in v 13.1.1

### ISSUE THREAD

**Issue by phyolim** [kubernetes-sigs/kui#9322]
**Describe the bug**
Logs live streaming doesn't load logs on 13.1.1. I tried v 12. It worked as expected.

**Steps to reproduce the behavior**

1. Open v 13.1.1
2. enter `kubectl get deploy`
3. select any deployment that has logs
4. Click on logs tab

**Expected behavior**
Expect logs to show up in the window

**Screenshots**
<img width="622" alt="Screenshot 2023-03-06 at 11 46 57 PM" src="https://user-images.githubusercontent.com/42676669/223332746-ed203884-093b-4f50-a126-d33f34143a52.png">

**System**

- Kui version: v13.1.1
- Operating system: mac os 13.12.1

**Comment by starpit** [comment]
hello, my apologies for the delay.

are you on apple silicon or intel? i think there are log streaming issues with apple silicon, and so were curious if you were also using that arch?

we shall investigate.

**Comment by phyolim** [comment]
I'm on Apple silicon.

**Comment by starpit** [comment]
a fix has been released in 13.1.3
