### ISSUE TITLE
Error starting up pty Error: node-loader after brew install

### ISSUE THREAD

**Issue by jmjava** [kubernetes-sigs/kui#9328]
I am trying to use kui installed with brew on my M1 Mac Ventura system

brew install kui

I have tried several versions of Node.js - currently trying with this version

Node.js v18.12.1

when i execute:

kubectl-kui get pods. 

I get the following error:

Error starting up pty Error: node-loader:
Error: The module '/Applications/Kui.app/Contents/Resources/app/dist/headless/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 99. This version of Node.js requires
NODE_MODULE_VERSION 110. Please try re-compiling or re-installing

I try reinstalling the module listed with npm rebuild /Applications/Kui.app/Contents/Resources/app/dist/headless/pty.node but it does not fix the issue.

I do get a window that lists the pods but it doesn't appear to be functioning fully.  The Terminal tab does not work.

Also, with Tekton pipelines, I do not get the "Flow" view.

**Comment by starpit** [comment]
hello there, thanks for opening the issue.

re: tekton, we have moved this to a separate repo. you can see it in action here: https://tekton.guidebooks.dev/
there, you will find a link to the github repo. we aren't sure what to do with this part. let us know if you have ideas!

**Comment by starpit** [comment]
re: pty, we shall investigate.

**Comment by starpit** [comment]
a pty fix has been released in 13.1.3
