### ISSUE TITLE
How to deploy kui hosted client-server in a k8s  server ?

### ISSUE THREAD

**Issue by gberche-orange** [kubernetes-sigs/kui#9331]
Thanks for sharing kui with the community !

### Expected

As a newcomer, 
In order to deploy kui into a k8s cluster
I need some support with pre-built client-server binaries with associated K8S deployment automation (K8S resources spec files, or helm chart)

### Observed

* https://github.com/kubernetes-sigs/kui/wiki/4.-Building-for-Production#i-want-to-build-for-a-hosted-application-service mentions building with local prereqs (npx)
* dockerhub images at https://hub.docker.com/r/kuishell/kui/tags seem not maintained
* github action tests seem to not separate the build phase from the browser test phase, and not deploy a hosted kui instance
   * https://github.com/kubernetes-sigs/kui/blob/master/.github/workflows/test.yaml , e.g. https://github.com/kubernetes-sigs/kui/actions/runs/4521706731/jobs/7963761268 phase "
* using cloud native buildpacks kpack cli (`kpack ./kui`) to build kui fails with some missing dependencies

**Comment by starpit** [comment]
hello there! thanks for the questions.

## Build image `kuishell/kui`

This will build a docker image `kuishell/kui` that includes the kui proxy and the kui client, and an nginx that will serve up both. It is also possible to build a "serverless" version that runs kui as a static single page web app.

```shell
npx kui-build-docker-with-proxy
```

## Test run it

```shell
npx kui-run-cproxy
```

then visit http://localhost:9080

If that works, then you are well on your way. For kube deployments, there is a sample yaml [here](https://github.com/kubernetes-sigs/kui/blob/v13.1.3/packages/proxy/deploy/kubernetes/client-proxy-combo.yaml).

From there, you can customize things, e.g. the favicon, app name, etc. Perhaps the best way to do this is to make your own kui client repo (you can start with the template: https://github.com/kui-shell/KuiClientTemplate).

from there, you can choose which kui plugins to include (see the package.json in the template). you can also configure icons and names in plugin-client-default/config.d/{icons,name}.json. The same build scripts above would work from the client template repo.

it is also possible to work off a fork of this main repo. but then, you wouldn't have the opportunity to be selective about which kui plugins to include in your service. nor would you be able to use npm semver to track base kui functionality. but both ways can work!

**Comment by starpit** [comment]
Some words of warning: the stock kui builds do not include an authentication scheme. So if you want to expose a full proxy-backed kui within a browser, this is something you will need to roll your own on.

**Comment by gberche-orange** [comment]
Many thanks @starpit for your prompt response !

In order to share the effort of building the container images, and speed up a sample kui k8s deployment, would it make sense to have the kui github workflow ci run the `npx kui-build-docker-with-proxy` command and publish the associated container image (e.g. in dockerhub or in the ghcr associated with this repo) ?

Should this github workflow and container images also or instead be located into the  https://github.com/kui-shell/KuiClientTemplate repo ?

This may also help people forking this repo either publicly or privately.

From there, it might make sense to extract the sample k8s yaml into a helm chart and see ways the UX customizations could be injected into the main image without requiring change to the kui-proxy and standard upstream  kui-client container image, such as:
- a second init container that overwrites the upstream kui-client content from git url, s3 content, OCI container image
- a mounted volume that overwrites the upstream kui-client content, such as from configmap(s) ?
