### ISSUE TITLE
Commands autocompletion is not working

### ISSUE THREAD

**Issue by satrox28** [kubernetes-sigs/kui#9335]
**Describe the bug**
Autocompletion commands are not working on kui shell, have to type the full commands or copy/paste the commands.

Related to this issue https://github.com/kubernetes-sigs/kui/issues/2885

**Steps to reproduce the behavior**

1. Type a command and press tab, doesn't show the autosuggestions/autocomplete.

**Expected behavior**
The commands to autocomplete

**System**

- Kui version: 13.1.3
- Operating system: macOS 13.1/zsh

**Comment by satrox28** [comment]
Hi Team, 

Do we have any update?.

**Comment by starpit** [comment]
hello! thanks for reporting this. could you add some commands that do not complete? i just tried `kube<tab> g<tab>` and got `kubectl get` 🤔 

thanks!

**Comment by jorpilo** [comment]
is there any way that kubectl <tab> show possible commands without having to add 1 letter?

**Comment by Dessix** [comment]
This appears to be actively reproing still. Some items complete, while others do not.

Out of this command:
`kubectl get -n my-namespace pods`
`kubectl`, `get`, `my-namespace` were able to tab-complete, while `pods` failed to complete from `po`, and multiple tab keypresses resulted in the focus changing to the hamburger-menu of the UI, then along the tab bar, losing focus on the text entirely.

It appears that - if completion fails to produce meaningful results - the tab press rotates focus along the page in a destructive manner. Oddly, attempting to complete from the already-completed word `pod` suppresses the issue, retaining the focus as if it is completing to the one available option and absorbing the tab press.
