### ISSUE TITLE
Uncaught TypeError exception after kubectl kui if kui window is already open

### ISSUE THREAD

**Issue by sergray** [kubernetes-sigs/kui#9351]
**Describe the bug**

Uncaught `TypeError` exception after `kubectl kui` if kui window is already open

**Steps to reproduce the behavior**

1. Install `kui` with `brew install kui`
2. Open terminal and run `kubectl kui`
3. kui window opens
4. Run `kubectl kui` in the terminal again
5. See error
    ```
    A JavaScript error occurred in the main process
    Uncaught Exception:
    TypeError: Cannot read properties of null (reading 'env')
    at App.<anonymous> (/Applications/Kui.app/Contents/Resources/app/dist/headless/7255.kui.min.js:1:15573)
    at App.emit (node:events:513:28)
    ```

**Expected behavior**
Focus goes to the open kui window and result of the command is shown there

**Screenshots**
Window with the error
![image](https://user-images.githubusercontent.com/195381/233359913-5d45c0d2-828a-4927-9d99-70782395f159.png)

**Code snippets**
Not applicable

**System**

- Kui version: v13.1.3
- Operating system: macOS Ventura 13.3.1 (22E261)

**Comment by starpit** [comment]
thanks for the bug report! we recently noticed this regression, too :(

we'll get on it!

**Comment by sergray** [comment]
Thank you very much for such a quick fix and release! I confirm it is
working.

Op do 20 apr. 2023 21:50 schreef Nick Mitchell ***@***.***>:
