### ISSUE TITLE
Update kubectl Logs tab to use xterm's search, rather than our home-grown

### ISSUE THREAD

**Issue by starpit** [kubernetes-sigs/kui#9359]
ours is nice, in that it filters to show only matching lines. but

1) sometimes i want to see context
2) we have to maintain lots of extra state on our side

**Comment by fkajerry** [comment]
@starpit Is it already done in this [PR](https://github.com/kubernetes-sigs/kui/pull/9182/files#diff-0e40f35208622aff1bf8c9aab6cfe77eb486f227c6777d002b85bb38a39fa353R22)

**Comment by starpit** [comment]
hello! no, this issue is still unresolved :(
